# Generated by Django 4.1.7 on 2023-02-28 15:45

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.FileField(null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='static/', validators=[my_store_app.models.Profile.validate_image]),
        ),
    ]
