# Generated by Django 4.1.7 on 2023-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0002_alter_categoryproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=True),
        ),
    ]
