# Generated by Django 4.1.7 on 2023-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0003_product_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feedback',
            field=models.IntegerField(default=0, verbose_name='счетчик комментариев'),
        ),
    ]
