# Generated by Django 4.1.7 on 2023-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0004_remove_product_free_delivery_product_limited_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='скидка % '),
        ),
    ]
